### ISSUE TITLE
Missing Structure

### ISSUE THREAD

**Issue by tunaeskanaytac** [Berkaytuncaa/Data-Structures-and-Algorithm#1]
Hello total stranger, as a fellow algorithm and data structures enthusiast myself, I can't help but notice that a very important structure in the data structures world, is, in fact, missing. And that wounds me very deeply the fact that I'm not able to see this structure in your very well designed book of data structures and algorithms. I encourage you to notice my intimate concerns for your well being and commit this structure for this repository to be full of its glory. I'm pretty sure which structure I'm talking about but since I wouldn't want to cause any misunderstanding with this issue, the structure I'm talking about is, surely, in fact, the Heap structure. Please do the appropriate thing to do and let this repository to reach its full potential to be the leading documentation of the algorithm world. Best Regards.

**Comment by Berkaytuncaa** [comment]
Howdy there, total Stranger,

I reckon your message hit me like a tumbleweed in a dust storm. You're darn tootin' right 'bout that heap missin' from the roundup. Well, saddle up, partner, 'cause we're fixin' to corral that heap structure and make this repository shine like a new pair of spurs. Much obliged for rustlin' up the concern, and may your algorithms ride off into the sunset.

Yeehaw and Happy Trailblazin',
Arthur Morgan

**Comment by Berkaytuncaa** [comment]
DONE
